name: 🚀 Auto-Deploy FTP

on:
  push:
    branches:
      - main # Se déclenche dès que ChatGPT fait le push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Récupérer le code
        uses: actions/checkout@v6

      - name: 📂 Push FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./test
